[package]
name = "rust-playground"
version = "0.1.0"
authors = ["Lars Melchior <TheLartians@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
ndarray = "0.14.0"
